apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cortex
  name: cortex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cortex
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cortex
    spec:
      containers:
      - image: thehiveproject/cortex:latest
        imagePullPolicy: ""
        name: cortex
        ports:
        - containerPort: 9001
          hostIP: 0.0.0.0
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
