apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: thehive
  name: thehive
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thehive
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: thehive
    spec:
      containers:
      - image: thehiveproject/thehive:latest
        imagePullPolicy: ""
        name: thehive
        ports:
        - containerPort: 9000
          hostIP: 0.0.0.0
        resources: {}
        volumeMounts:
        - mountPath: /etc/thehive/application.conf
          name: thehive-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: thehive-claim0
        persistentVolumeClaim:
          claimName: thehive-claim0
status: {}
